version: '3'

services:
  web-mols:
    container_name: web-mols
    build: .
    env_file:
      - .env
    command: bash -c "
      uvicorn app.main:app
      --host 0.0.0.0 --port 8080
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload  --reload-dir /source/app --reload-dir /source/tests
      "
    volumes:
      - .:/source/
    ports:
      - 8080:8080
    depends_on:
      - redis-mols

  redis-mols:
    container_name: redis-mols
    image: redis:latest
    restart: always
    env_file:
      - .env
    command: redis-server --port "${REDIS_PORT}" --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - 6379:6379

